// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj-Yjyjnii8jAkVikdY1HAkI8laju45IE',
    appId: '1:853475216489:web:cee6a39bce8f46c191e6f8',
    messagingSenderId: '853475216489',
    projectId: 'wishlistapp-28558',
    authDomain: 'wishlistapp-28558.firebaseapp.com',
    storageBucket: 'wishlistapp-28558.firebasestorage.app',
    measurementId: 'G-WRYS3CQ7YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhakmWa-zx-xjaFBPKwWDQ58qhG4eTnmM',
    appId: '1:853475216489:android:abdd742d232d48e491e6f8',
    messagingSenderId: '853475216489',
    projectId: 'wishlistapp-28558',
    storageBucket: 'wishlistapp-28558.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzinOiN4c1dffEi9bfOJ7YJrzq0ajhivA',
    appId: '1:853475216489:ios:80d775be836c968191e6f8',
    messagingSenderId: '853475216489',
    projectId: 'wishlistapp-28558',
    storageBucket: 'wishlistapp-28558.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzinOiN4c1dffEi9bfOJ7YJrzq0ajhivA',
    appId: '1:853475216489:ios:80d775be836c968191e6f8',
    messagingSenderId: '853475216489',
    projectId: 'wishlistapp-28558',
    storageBucket: 'wishlistapp-28558.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj-Yjyjnii8jAkVikdY1HAkI8laju45IE',
    appId: '1:853475216489:web:47f6f74375df36e791e6f8',
    messagingSenderId: '853475216489',
    projectId: 'wishlistapp-28558',
    authDomain: 'wishlistapp-28558.firebaseapp.com',
    storageBucket: 'wishlistapp-28558.firebasestorage.app',
    measurementId: 'G-KSS1YCS98F',
  );
}
